-- Check all Chronology games and their draw piles
SELECT 
    L.NAME AS LobbyName,
    CG.ID AS GameId,
    CG.GAME_STATUS,
    (SELECT COUNT(*) FROM CHRONOLOGY_DRAW_PILE WHERE CHRONOLOGY_GAME_ID = CG.ID) AS DrawPileSize,
    (SELECT COUNT(*) FROM CHRONOLOGY_DRAW_PILE WHERE CHRONOLOGY_GAME_ID = CG.ID AND CARD_YEAR > 0) AS CardsWithYears,
    (SELECT COUNT(*) FROM CHRONOLOGY_CURRENT_CARD WHERE CHRONOLOGY_GAME_ID = CG.ID) AS CurrentCards
FROM CHRONOLOGY_GAME CG
INNER JOIN LOBBY L ON L.ID = CG.LOBBY_ID
ORDER BY CG.CREATED_ON_DATE DESC;

-- Show what's actually in the draw pile
SELECT 
    L.NAME AS LobbyName,
    C.TEXT AS CardText,
    DP.CARD_YEAR AS ExtractedYear,
    DP.DRAWN AS IsDrawn
FROM CHRONOLOGY_DRAW_PILE DP
INNER JOIN CHRONOLOGY_GAME CG ON CG.ID = DP.CHRONOLOGY_GAME_ID
INNER JOIN LOBBY L ON L.ID = CG.LOBBY_ID
INNER JOIN CARD C ON C.ID = DP.CARD_ID;
