CREATE TABLE IF NOT EXISTS CHRONOLOGY_GAME(
    ID UUID NOT NULL DEFAULT UUID(),
    LOBBY_ID UUID NOT NULL,
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CURRENT_PLAYER_ID UUID NULL,
    GAME_STATUS ENUM('waiting', 'active', 'finished') NOT NULL DEFAULT 'waiting',
    CARDS_TO_WIN INT NOT NULL DEFAULT 5,
    WINNER_ID UUID NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(LOBBY_ID) REFERENCES LOBBY(ID) ON DELETE CASCADE,
    FOREIGN KEY(CURRENT_PLAYER_ID) REFERENCES PLAYER(ID) ON DELETE SET NULL,
    FOREIGN KEY(WINNER_ID) REFERENCES USER(ID) ON DELETE SET NULL,
    CONSTRAINT LOBBY_UNIQUE UNIQUE(LOBBY_ID)
);
