-- Tracks each player's timeline (cards they've correctly placed)
CREATE TABLE IF NOT EXISTS CHRONOLOGY_PLAYER_TIMELINE(
    ID UUID NOT NULL DEFAULT UUID(),
    CHRONOLOGY_GAME_ID UUID NOT NULL,
    PLAYER_ID UUID NOT NULL,
    CARD_ID UUID NOT NULL,
    CARD_YEAR INT NOT NULL,
    POSITION INT NOT NULL,
    PLACED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY(ID),
    FOREIGN KEY(CHRONOLOGY_GAME_ID) REFERENCES CHRONOLOGY_GAME(ID) ON DELETE CASCADE,
    FOREIGN KEY(PLAYER_ID) REFERENCES PLAYER(ID) ON DELETE CASCADE,
    FOREIGN KEY(CARD_ID) REFERENCES CARD(ID) ON DELETE CASCADE,
    CONSTRAINT GAME_PLAYER_CARD_UNIQUE UNIQUE(CHRONOLOGY_GAME_ID, PLAYER_ID, CARD_ID)
);
