-- Current card being played (one per game at a time)
CREATE TABLE IF NOT EXISTS CHRONOLOGY_CURRENT_CARD(
    ID UUID NOT NULL DEFAULT UUID(),
    CHRONOLOGY_GAME_ID UUID NOT NULL,
    CARD_ID UUID NOT NULL,
    CARD_YEAR INT NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(CHRONOLOGY_GAME_ID) REFERENCES CHRONOLOGY_GAME(ID) ON DELETE CASCADE,
    FOREIGN KEY(CARD_ID) REFERENCES CARD(ID) ON DELETE CASCADE,
    CONSTRAINT GAME_UNIQUE UNIQUE(CHRONOLOGY_GAME_ID)
);
