CREATE TABLE IF NOT EXISTS LOBBY(
    ID UUID NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    NAME VARCHAR(255) NOT NULL,
    GAME_TYPE ENUM('cah', 'chronology') NOT NULL DEFAULT 'cah',
    MESSAGE VARCHAR(255) NULL,
    PASSWORD_HASH CHAR(60) NULL,
    DRAW_PRIORITY ENUM('RANDOM', 'PLAYCOUNT') NOT NULL DEFAULT 'RANDOM',
    HAND_SIZE INT NOT NULL DEFAULT 8,
    FREE_CREDITS INT NOT NULL DEFAULT 3,
    WIN_STREAK_THRESHOLD INT NOT NULL DEFAULT 3,
    LOSE_STREAK_THRESHOLD INT NOT NULL DEFAULT 3,
    ROUND_ID UUID NOT NULL DEFAULT UUID(),
    PRIMARY KEY(ID),
    CONSTRAINT NAME_UNIQUE UNIQUE(NAME)
);