-- Draw pile for Timeline Trivia games (cards available to draw)
CREATE TABLE IF NOT EXISTS TIMELINE_TRIVIA_DRAW_PILE(
    ID UUID NOT NULL DEFAULT UUID(),
    TIMELINE_TRIVIA_GAME_ID UUID NOT NULL,
    CARD_ID UUID NOT NULL,
    CARD_YEAR INT NOT NULL,
    DRAWN BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY(ID),
    FOREIGN KEY(TIMELINE_TRIVIA_GAME_ID) REFERENCES TIMELINE_TRIVIA_GAME(ID) ON DELETE CASCADE,
    FOREIGN KEY(CARD_ID) REFERENCES CARD(ID) ON DELETE CASCADE,
    CONSTRAINT GAME_CARD_UNIQUE UNIQUE(TIMELINE_TRIVIA_GAME_ID, CARD_ID)
);
