-- Tracks each player's incorrect guess on the currently-active card (steal
-- mechanic). At most one attempt per player per card round; cleared whenever
-- the round resolves (a correct guess or every active player has missed).
CREATE TABLE IF NOT EXISTS TIMELINE_TRIVIA_CARD_ATTEMPT(
    ID UUID NOT NULL DEFAULT UUID(),
    TIMELINE_TRIVIA_GAME_ID UUID NOT NULL,
    PLAYER_ID UUID NOT NULL,
    POSITION INT NOT NULL,
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY(ID),
    FOREIGN KEY(TIMELINE_TRIVIA_GAME_ID) REFERENCES TIMELINE_TRIVIA_GAME(ID) ON DELETE CASCADE,
    FOREIGN KEY(PLAYER_ID) REFERENCES PLAYER(ID) ON DELETE CASCADE,
    CONSTRAINT GAME_PLAYER_UNIQUE UNIQUE(TIMELINE_TRIVIA_GAME_ID, PLAYER_ID)
);
