CREATE TABLE IF NOT EXISTS TIMELINE_TRIVIA_GAME(
    ID UUID NOT NULL DEFAULT UUID(),
    LOBBY_ID UUID NOT NULL,
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    -- CURRENT_PLAYER_ID is whoever is being asked to guess right now (may be
    -- stealing after another player missed). ROUND_STARTER_PLAYER_ID is who
    -- the card round began with; the next round always resumes at the next
    -- active player after the STARTER, regardless of who wins the steal.
    CURRENT_PLAYER_ID UUID NULL,
    ROUND_STARTER_PLAYER_ID UUID NULL,
    GAME_STATUS ENUM('waiting', 'active', 'finished') NOT NULL DEFAULT 'waiting',
    CARDS_TO_WIN INT NOT NULL DEFAULT 5,
    WINNER_ID UUID NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(LOBBY_ID) REFERENCES LOBBY(ID) ON DELETE CASCADE,
    FOREIGN KEY(CURRENT_PLAYER_ID) REFERENCES PLAYER(ID) ON DELETE SET NULL,
    FOREIGN KEY(ROUND_STARTER_PLAYER_ID) REFERENCES PLAYER(ID) ON DELETE SET NULL,
    FOREIGN KEY(WINNER_ID) REFERENCES USER(ID) ON DELETE SET NULL,
    CONSTRAINT LOBBY_UNIQUE UNIQUE(LOBBY_ID)
);
